theme:
  name: mkdocs
  local: en
  color_mode: auto
  nav_style: primary
  highlightjs: True
  hljs_style: github
  hljs_style_dark: github_dark

site_name: Documentation Pipeline BILL
repo_url: https://github.com/asfistonlavie/BILL
repo_name: BILL
site_description: Documentation of BILL's Pipeline
site_author: Catherine Breton, Anna-Sophie Fiston-Lavier, Arnaud Soulier

nav:
  - Home: index.md
  - Preprocessing: preprocessing.md
  - Mapping: mapping.md
  - SV calling: calling.md
  - About: about.md
