theme:
  name: mkdocs
  local: en
  color_mode: auto
  nav_style: primary

site_name: Documentation Pipeline BILL
repo_url: https://github.com/asfistonlavie/BILL
edit_uri: edit/main/docs/
site_description: Documentation of BILL's Pipeline
site_author: Catherine Breton, Anna-Sophie Fiston-Lavier, Arnaud Soulier

nav:
  - Home: 'index.md'
  - Preprocessing: 'preprocessing.md'
  - Mapping: 'mapping.md'
  - Variant calling: 'calling.md'
  - About: 'about.md'
