#######################
### Required values ###
#######################

input_dir: 'ressources/inputs/P15'
ref_dir: 'ressources/references'
ref_name: 'KHV-U_trunc.fasta'

########################
### Adaptable values ###
########################

res_dir: 'results/P15-on-KHVU_trunc'
samples: ['P15-1','P15-2','P15-3','P15-4','P15-5','P15-6','P15-7','P15-8','P15-9','P15-10']
trim: 1000
group: 'P15'

######################
### Default values ###
######################

seqkit_stats_options: '-a'
seqkit_seq_options: '-g'
minimap2_options: '--MD -ax map-ont'
samtools_flagstat_options: ''
python_flagstat_plot_options: ''
samtools_view_options: '-bhS -F 4'
samtools_sort_options: '-l 9'
samtools_index_options: ''
bamCoverage_options: '--normalizeUsing RPGC -of "bedgraph"'
plotCoverage_options: '--smartLabels --plotFileFormat pdf'
sniffles_options: '--minsvlen 10 --minsupport 10'
cutesv_options: '--min_size 10 --min_support 10 --genotype'
svim_options: '--min_sv_size 10'
nanovar_options: '--minlen 10 --mincov 10'
nanosv_options: ''
bcftools_stats_options: ''
combisv_options: ''
bcftools_filter_options: '-e "AF<0.1"'
bgzip_options: ''
tabix_options: ''
bcftools_merge_options: ''
medaka_consensus_options: ''
medaka_snp_options: ''
medaka_stitch_options: ''
