__default__:
    job-name: "{rule}"
    queue: "fast"
    nodes: "--nodes=1"
    cpus: "--cpus-per-task=1"
    mem: "--mem=1G"
    log: "--output=LOGS/P1/{rule}.log"

seqkit_trim:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=2"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/SEQKIT/{rule}.log"

minimap2:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=4"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/MINIMAP2/{rule}.log"

samtools_view:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=2"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/SAMTOOLS/{rule}.log"

samtools_sort:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=2"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/SAMTOOLS/{rule}.log"

samtools_flagstat:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=2"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/SAMTOOLS/{rule}.log"

samtools_index:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=2"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/SAMTOOLS/{rule}.log"

bam_coverage:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=4"
    mem: "--mem=8G"
    log: "--output=LOGS/P1/DEEPTOOLS/{rule}.log"

plot_coverage:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=8"
    mem: "--mem=64G"
    log: "--output=LOGS/P1/DEEPTOOLS/{rule}.log"

sniffles:
    job-name: "{rule}:{wildcards.sample}"
    cpus: "--cpus-per-task=4"
    mem: "--mem=16G"
    log: "--output=LOGS/P1/SNIFFLES/{rule}.log"
